### ISSUE TITLE
Use gpu indirect call on web

### ISSUE THREAD

**Issue by happydpc** [BVE-Reborn/rend3#202]
Now it uses indirect draw count extension. But on browser webgpu, it can only use draw_indirect. That means if we can use the copy buffer to the cpu, and draw the visible call. Wondering how to implement this copy and draw again.

**Comment by cwfitzgerald** [comment]
Currently we do the culling CPU side the whole time in CPU mode. Most of the overhead of CPU side is recording the commands at all vs doing the culling, so there's no real reason to force a readback. I'm especially apprehensive on WebGPU because GPU -> CPU readback on WebGPU is going to have signification overhead due to the marshaling overhead. 

There will eventually be a multi-draw-indirect extension to WebGPU, so I'd prefer to wait/adapt to that before trying to make CPU mode bend over backwards to do more. Part of the point of CPU mode is that it basically uses no features, so it can run on basically any device. Requiring indirect would actually limit some of these options.
