### ISSUE TITLE
Improve Library Documentation for Window Lifetimes

### ISSUE THREAD

**Issue by John-Nagle** [BVE-Reborn/rend3#315]
Rend3 started as "an easy to use, customizable, efficient 3D renderer library built on wgpu." And, for over a year, it was. The direction seemed to be safe concurrency, with multi-thread access to Rend3's objects. 

Now, though, it appears that Rend3 is changing to a framework, and one heavily based on "async" and Tokio.  Changing Rend3 from a library to a framework (you call a library, a framework calls you) puts Rend3 at the top of the food chain and gives Rend3 control over startup and the event loop.  In some ways, that's a win. But it's a huge headache for something designed to use Rend3 as a library. 

Inside my code, Rend3 is off in a corner with its own high priority thread, running a small, endless rendering loop that does little else. That keeps the frame rate high, or should, regardless of anything else going on. All changes to the scene come from other threads running concurrently. Coordination is primarily through fine-grained locking on parts of the scene graph. A more channel-oriented approach was tried, where one thread owned the scene graph, but that led to excessive complexity where the scene graph had changed while something was queued on a channel, requiring resolving an out-of-sync condition. Fine-grained locking is working, and I'd like to stay with that.

The "rend3-framework", though, forces the use of "async", and something like Tokio to drive it. This is a concern. Once started down that path, such a framework tends to determine the program architecture. Gradually, "async" creeps into everything.

Multithread async with compute-bound code isn't a good match to Tokio, says the Tokio documentation.  "Async" is really intended for I/O bound systems. It is something of a mismatch to game systems where several CPUs are running at 100%. 

So I'm concerned about async becoming a user-visible part of the Rend3 API.

**Comment by cwfitzgerald** [comment]
Thanks for filing!

> Now, though, it appears that Rend3 is changing to a framework, and one heavily based on "async" and Tokio.

To clarify, rend3-framework is designed to be, and will always be, and optional component in the rend3 ecosystem. It will continue to be "implemented in user space" as part of a separate crate. For people who are integrating with existing applications or otherwise have complex requirements rend3-framework should be ignored (or at most cribbed from) as it solves a different problem. 

For people who have a new application and have no strong custom windowing requirements, the framework serves as a means for those users to not have to write the (rather tedious) code to make the program work on all platforms, including mobile and web, both which have fun quirks compared to desktop. I intend to keep the framework pretty lean and serving this specific use case.

I want to make sure this is very clear in the documentation (which #275 the next and final step towards a 0.3 release) and I will continue to maintain the "frameworkless" example so it remains easy to see how the parts all fit together without a framework obscuring the callstacks. If there's any spot in particular you think this should be highlighted/augmented, let me know.

> The "rend3-framework", though, forces the use of "async", and something like Tokio to drive it. This is a concern. Once started down that path, such a framework tends to determine the program architecture. Gradually, "async" creeps into everything.

The async was introduced in the framework because wasm requires it -- fundamentally the framework still behaves the same as the framework-less examples, it still calls pollster::block_on() on native to turn "async" into synchronous code. On wasm we use the browser's builtin async executor for this task.

I agree, async has the "red/blue code" problem, so I'm trying to limit its use throughout to where wgpu requires it. The only thing that requires it in any of the non-framework crates is create_iad, and this is just bubbling up the async from wgpu, and can be blocked on easily.

~~On looking at the design, the explicit tokio dep isn't needed, it's only used for the `spawn` function, which really can be emulated with thread::spawn(block_on(t)).~~ Turns out I already did that, the framework doesn't have a tokio dep.

> Multithread async with compute-bound code isn't a good match to Tokio, says the Tokio documentation. "Async" is really intended for I/O bound systems. It is something of a mismatch to game systems where several CPUs are running at 100%.

Tokio definitely isn't suited for this, I think async in general can be (and I even made an executor to help with that https://github.com/BVE-Reborn/switchyard), but I also think this is a very heavy-handed design which I would never want to force on my users. (I have even moved away from this architecture for various projects in favor of simple multithreading + rayon when needed)

Hope that clarifies things.

**Comment by John-Nagle** [comment]
Thanks. It's good to hear that.

In that case, more library-type help with the initialization boilerplate would be helpful.

With each new version of Rend3, I've had to rewrite my initialization code, using scene-viewer as a model. A non-framework scene-viewer would be helpful as a model, especially if it had egui support. That area is delicate, because there is a line of unsafe code and order of destruction has to be manually managed to avoid dropping the window before all destructors in all threads have run. That's the only area that has generated segfaults in a year.

**Comment by cwfitzgerald** [comment]
Alright, I think this is something that we can call out in both the comments in the cube-no-framework example, and on the docs that will eventually populate the website. 

I'm going to leave this issue open until at least there is documentation in the example about what the destruction order needs to be.

**Comment by John-Nagle** [comment]
Thanks. I realize I'm looking at the code before documentation and release. 
I'm struggling to figure out how to reconcile my program's architecture with Rend3 in the Android/WASM era. It gets complicated trying to make the same code work with such different models. Yet all that cross-platform compatibility is very nice.

Mixed threading and async is complicated.

**Comment by cwfitzgerald** [comment]
If you don't need the weirdness of android or of wasm, you can just leave your program structure the way it is, plop the new graph code wherever you called the old render routines and call it a day.
